apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rzp44qps8-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-90767d4692.zja9.p3.openshiftapps.com/rhtap/rhtap-qe:1b86d73d80e5c8efe501acea4f2a178a31a6dfa5@sha256:67bd4b331754b01aa8e5cf66ec2a224c657bf893ab64cfb7b84b530d0d941e41
          name: container-image
